// Demo product catalog (no backend, static data)
const PRODUCTS = [
  // Clothing
  { id: 1, name: "Urban Jacket", cat: "clothing", price: 59.99, emoji: "🧥", desc: "Lightweight, water-resistant jacket." },
  { id: 2, name: "Basic T-Shirt", cat: "clothing", price: 14.99, emoji: "👕", desc: "100% cotton, regular fit." },
  { id: 4, name: "Classic Cap", cat: "clothing", price: 11.99, emoji: "🧢", desc: "Adjustable, one size fits all." },
  { id: 16, name: "Urban Backpack", cat: "clothing", price: 39.99, emoji: "🎒", desc: "Padded laptop compartment." },
  { id: 17, name: "Jeans", cat: "clothing", price: 38.99, emoji: "👖", desc: "Straight cut, durable denim." },
  { id: 18, name: "Hoodie", cat: "clothing", price: 34.99, emoji: "🧶", desc: "Fleece-lined interior, extra warm." },
  { id: 19, name: "Casual Dress", cat: "clothing", price: 44.99, emoji: "👗", desc: "Lightweight fabric, perfect for everyday wear." },
  { id: 20, name: "Wool Scarf", cat: "clothing", price: 19.99, emoji: "🧣", desc: "Soft and warm for winter." },
  { id: 21, name: "Winter Gloves", cat: "clothing", price: 13.99, emoji: "🧤", desc: "Thermal lining, one size." },
  { id: 22, name: "Sock Pack", cat: "clothing", price: 9.99, emoji: "🧦", desc: "Pack of 5 pairs, cotton." },
  { id: 23, name: "Leather Belt", cat: "clothing", price: 21.99, emoji: "👞", desc: "Genuine leather, metal buckle." },
  { id: 24, name: "Swimsuit", cat: "clothing", price: 27.99, emoji: "🩳", desc: "Quick-dry, UV protection." },
  { id: 25, name: "Pajama Set", cat: "clothing", price: 25.99, emoji: "🩱", desc: "Soft cotton, top and bottoms." },
  { id: 26, name: "Long Coat", cat: "clothing", price: 74.99, emoji: "🧥", desc: "Elegant cut for cold weather." },

  // Electronics
  { id: 5, name: "Wireless Headphones", cat: "electronics", price: 89.99, emoji: "🎧", desc: "Active noise cancellation." },
  { id: 6, name: "Smartwatch Pulse", cat: "electronics", price: 119.99, emoji: "⌚", desc: "Heart rate monitor and GPS." },
  { id: 7, name: "Mechanical Keyboard", cat: "electronics", price: 59.99, emoji: "⌨️", desc: "Tactile switches, backlit." },
  { id: 8, name: "Portable Speaker", cat: "electronics", price: 39.99, emoji: "🔊", desc: "12-hour battery, water-resistant." },
  { id: 27, name: "30W USB-C Charger", cat: "electronics", price: 17.99, emoji: "🔌", desc: "Fast charging for phones and tablets." },
  { id: 28, name: "10000mAh Power Bank", cat: "electronics", price: 29.99, emoji: "🔋", desc: "Dual USB port, fast charging." },
  { id: 29, name: "Wireless Mouse", cat: "electronics", price: 19.99, emoji: "🖱️", desc: "High-precision optical sensor." },
  { id: 30, name: "24-inch Monitor", cat: "electronics", price: 149.99, emoji: "🖥️", desc: "Full HD, IPS panel." },
  { id: 31, name: "HD Webcam", cat: "electronics", price: 33.99, emoji: "📷", desc: "1080p with built-in microphone." },
  { id: 32, name: "WiFi 6 Router", cat: "electronics", price: 64.99, emoji: "📶", desc: "High-speed coverage for your home." },
  { id: 33, name: "1TB External Hard Drive", cat: "electronics", price: 49.99, emoji: "💾", desc: "Compact, USB 3.0 connection." },
  { id: 34, name: "10\" Tablet", cat: "electronics", price: 179.99, emoji: "📱", desc: "Crisp display, long battery life." },
  { id: 35, name: "HDMI Cable 2m", cat: "electronics", price: 8.99, emoji: "🔗", desc: "Supports 4K resolution." },
  { id: 36, name: "Laptop Stand", cat: "electronics", price: 23.99, emoji: "💻", desc: "Adjustable, improves ergonomics." },

  // Home
  { id: 9, name: "Frying Pan Set", cat: "home", price: 42.99, emoji: "🍳", desc: "Non-stick, 3 pieces." },
  { id: 10, name: "Desk Lamp", cat: "home", price: 21.99, emoji: "💡", desc: "Dimmable LED light." },
  { id: 11, name: "Artificial Plant", cat: "home", price: 16.99, emoji: "🪴", desc: "Maintenance-free decoration." },
  { id: 12, name: "Towel Set", cat: "home", price: 25.99, emoji: "🧺", desc: "Soft cotton, pack of 4." },
  { id: 37, name: "Bedsheet Set", cat: "home", price: 31.99, emoji: "🛏️", desc: "Soft microfiber, includes pillowcases." },
  { id: 38, name: "Blackout Curtains", cat: "home", price: 28.99, emoji: "🪟", desc: "Blocks light, pair of panels." },
  { id: 39, name: "Wall Mirror", cat: "home", price: 36.99, emoji: "🪞", desc: "Round frame, modern finish." },
  { id: 40, name: "Closet Organizer", cat: "home", price: 19.99, emoji: "🗄️", desc: "Stackable, foldable compartments." },
  { id: 41, name: "Aroma Diffuser", cat: "home", price: 24.99, emoji: "🕯️", desc: "With LED light and auto shut-off." },
  { id: 42, name: "Knife Set", cat: "home", price: 34.99, emoji: "🔪", desc: "Stainless steel, 5 pieces." },
  { id: 43, name: "Cutting Board", cat: "home", price: 12.99, emoji: "🪵", desc: "Bamboo wood, double-sided." },
  { id: 44, name: "Decorative Rug", cat: "home", price: 38.99, emoji: "🧵", desc: "Non-slip, easy to clean." },
  { id: 45, name: "Laundry Basket", cat: "home", price: 16.99, emoji: "🧺", desc: "Foldable, reinforced handles." },
  { id: 46, name: "Wall Clock", cat: "home", price: 18.99, emoji: "🕰️", desc: "Silent movement, minimalist design." },

  // Sports
  { id: 3, name: "Running Shoes", cat: "sports", price: 74.99, emoji: "👟", desc: "Cushioning for long distances." },
  { id: 13, name: "Soccer Ball", cat: "sports", price: 24.99, emoji: "⚽", desc: "Official size 5." },
  { id: 14, name: "5kg Dumbbells (pair)", cat: "sports", price: 29.99, emoji: "🏋️", desc: "Rubber coating." },
  { id: 15, name: "Thermal Bottle", cat: "sports", price: 15.99, emoji: "🚰", desc: "Keeps drinks cold or hot for 12h." },
  { id: 47, name: "Yoga Mat", cat: "sports", price: 21.99, emoji: "🧘", desc: "Non-slip, includes strap." },
  { id: 48, name: "Jump Rope", cat: "sports", price: 8.99, emoji: "➰", desc: "Smooth bearings, adjustable." },
  { id: 49, name: "Boxing Gloves", cat: "sports", price: 32.99, emoji: "🥊", desc: "High-density padding." },
  { id: 50, name: "Resistance Band Set", cat: "sports", price: 10.99, emoji: "🎗️", desc: "Set of 3 resistance levels." },
  { id: 51, name: "Foldable Exercise Bike", cat: "sports", price: 139.99, emoji: "🚲", desc: "Monitor display, space-saving." },
  { id: 52, name: "Cycling Helmet", cat: "sports", price: 39.99, emoji: "🚴", desc: "Ventilated and adjustable." },
  { id: 53, name: "Sports Knee Pads", cat: "sports", price: 13.99, emoji: "🦵", desc: "Compression and joint support." },
  { id: 54, name: "Sports Whistle", cat: "sports", price: 4.99, emoji: "🔔", desc: "Sharp sound, with lanyard." },
  { id: 55, name: "Sports Bag", cat: "sports", price: 25.99, emoji: "👜", desc: "Dedicated shoe compartment." },
  { id: 56, name: "Sports GPS Watch", cat: "sports", price: 94.99, emoji: "⌚", desc: "Route and heart-rate tracking." },

  // Fruits
  { id: 57, name: "Apples", cat: "fruits", price: 2.49, emoji: "🍎", desc: "1kg bag, fresh and crisp." },
  { id: 58, name: "Bananas", cat: "fruits", price: 1.79, emoji: "🍌", desc: "Bunch of 6." },
  { id: 59, name: "Oranges", cat: "fruits", price: 2.19, emoji: "🍊", desc: "1kg bag, juicy." },
  { id: 60, name: "Strawberries", cat: "fruits", price: 3.49, emoji: "🍓", desc: "250g box, sweet and fresh." },
  { id: 61, name: "Grapes", cat: "fruits", price: 3.99, emoji: "🍇", desc: "Seedless bunch, 500g." },
  { id: 62, name: "Pineapple", cat: "fruits", price: 2.99, emoji: "🍍", desc: "One unit, perfectly ripe." },
  { id: 63, name: "Watermelon", cat: "fruits", price: 5.49, emoji: "🍉", desc: "Large, extra juicy." },
  { id: 64, name: "Mango", cat: "fruits", price: 2.79, emoji: "🥭", desc: "Bag of 3." },
  { id: 65, name: "Kiwi", cat: "fruits", price: 3.19, emoji: "🥝", desc: "Tray of 6." },
  { id: 66, name: "Avocado", cat: "fruits", price: 4.49, emoji: "🥑", desc: "Bag of 3, ready to eat." },

  // Groceries
  { id: 67, name: "Whole Milk 1L", cat: "groceries", price: 1.29, emoji: "🥛", desc: "Fresh pasteurized milk." },
  { id: 68, name: "Eggs (dozen)", cat: "groceries", price: 2.49, emoji: "🥚", desc: "Fresh farm eggs." },
  { id: 69, name: "Sliced Bread", cat: "groceries", price: 2.19, emoji: "🍞", desc: "White bread, 680g." },
  { id: 70, name: "Cola Soda 2L", cat: "groceries", price: 1.99, emoji: "🥤", desc: "2-liter bottle." },
  { id: 71, name: "Rice 1kg", cat: "groceries", price: 1.49, emoji: "🍚", desc: "Long grain, premium quality." },
  { id: 72, name: "Sugar 1kg", cat: "groceries", price: 1.39, emoji: "🧂", desc: "Standard refined sugar." },
  { id: 73, name: "Vegetable Oil 1L", cat: "groceries", price: 3.29, emoji: "🫙", desc: "Great for cooking and frying." },
  { id: 74, name: "Ground Coffee 250g", cat: "groceries", price: 4.49, emoji: "☕", desc: "Medium roast, rich aroma." },
  { id: 75, name: "Pasta 500g", cat: "groceries", price: 1.19, emoji: "🍝", desc: "Spaghetti-style pasta." },
  { id: 76, name: "Canned Tuna (3-pack)", cat: "groceries", price: 3.79, emoji: "🐟", desc: "In water, pack of 3 cans." },

  // Miscellaneous
  { id: 77, name: "AA Batteries (4-pack)", cat: "misc", price: 3.49, emoji: "🔋", desc: "Long-lasting alkaline batteries." },
  { id: 78, name: "Toilet Paper (12-pack)", cat: "misc", price: 6.99, emoji: "🧻", desc: "Two-ply, soft." },
  { id: 79, name: "Liquid Detergent 1L", cat: "misc", price: 5.29, emoji: "🧴", desc: "For laundry, fresh scent." },
  { id: 80, name: "LED Bulbs (2-pack)", cat: "misc", price: 3.99, emoji: "💡", desc: "Low energy, warm light." },
  { id: 81, name: "Folding Umbrella", cat: "misc", price: 9.99, emoji: "☂️", desc: "Compact, wind-resistant." },
  { id: 82, name: "Lighter (2-pack)", cat: "misc", price: 1.49, emoji: "🔥", desc: "Easy and safe ignition." },
  { id: 83, name: "Adhesive Tape", cat: "misc", price: 1.79, emoji: "📏", desc: "Clear multi-purpose roll." },
  { id: 84, name: "Trash Bags (roll of 30)", cat: "misc", price: 2.99, emoji: "🗑️", desc: "Durable, standard size." },
  { id: 85, name: "Scented Candles (set of 3)", cat: "misc", price: 7.49, emoji: "🕯️", desc: "Assorted relaxing scents." },
  { id: 86, name: "Multi-tool Keychain", cat: "misc", price: 2.89, emoji: "🔑", desc: "Includes bottle opener and flashlight." },
];
